# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/larryytr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/larryytr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/larryytr/Grade3_1/advanced_programming/Homework/design_2/work/PVZ

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/larryytr/Grade3_1/advanced_programming/Homework/design_2/work/PVZ

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/larryytr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/larryytr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/larryytr/Grade3_1/advanced_programming/Homework/design_2/work/PVZ/CMakeFiles /home/larryytr/Grade3_1/advanced_programming/Homework/design_2/work/PVZ/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/larryytr/Grade3_1/advanced_programming/Homework/design_2/work/PVZ/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PVZ

# Build rule for target.
PVZ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PVZ
.PHONY : PVZ

# fast build rule for target.
PVZ/fast:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/build
.PHONY : PVZ/fast

src/Controller.o: src/Controller.cpp.o

.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i

.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s

.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/ScreenDraw_linux.o: src/ScreenDraw_linux.cpp.o

.PHONY : src/ScreenDraw_linux.o

# target to build an object file
src/ScreenDraw_linux.cpp.o:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/ScreenDraw_linux.cpp.o
.PHONY : src/ScreenDraw_linux.cpp.o

src/ScreenDraw_linux.i: src/ScreenDraw_linux.cpp.i

.PHONY : src/ScreenDraw_linux.i

# target to preprocess a source file
src/ScreenDraw_linux.cpp.i:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/ScreenDraw_linux.cpp.i
.PHONY : src/ScreenDraw_linux.cpp.i

src/ScreenDraw_linux.s: src/ScreenDraw_linux.cpp.s

.PHONY : src/ScreenDraw_linux.s

# target to generate assembly for a file
src/ScreenDraw_linux.cpp.s:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/ScreenDraw_linux.cpp.s
.PHONY : src/ScreenDraw_linux.cpp.s

src/linux_env.o: src/linux_env.cpp.o

.PHONY : src/linux_env.o

# target to build an object file
src/linux_env.cpp.o:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/linux_env.cpp.o
.PHONY : src/linux_env.cpp.o

src/linux_env.i: src/linux_env.cpp.i

.PHONY : src/linux_env.i

# target to preprocess a source file
src/linux_env.cpp.i:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/linux_env.cpp.i
.PHONY : src/linux_env.cpp.i

src/linux_env.s: src/linux_env.cpp.s

.PHONY : src/linux_env.s

# target to generate assembly for a file
src/linux_env.cpp.s:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/linux_env.cpp.s
.PHONY : src/linux_env.cpp.s

src/logic.o: src/logic.cpp.o

.PHONY : src/logic.o

# target to build an object file
src/logic.cpp.o:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/logic.cpp.o
.PHONY : src/logic.cpp.o

src/logic.i: src/logic.cpp.i

.PHONY : src/logic.i

# target to preprocess a source file
src/logic.cpp.i:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/logic.cpp.i
.PHONY : src/logic.cpp.i

src/logic.s: src/logic.cpp.s

.PHONY : src/logic.s

# target to generate assembly for a file
src/logic.cpp.s:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/logic.cpp.s
.PHONY : src/logic.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PVZ.dir/build.make CMakeFiles/PVZ.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... PVZ"
	@echo "... edit_cache"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/ScreenDraw_linux.o"
	@echo "... src/ScreenDraw_linux.i"
	@echo "... src/ScreenDraw_linux.s"
	@echo "... src/linux_env.o"
	@echo "... src/linux_env.i"
	@echo "... src/linux_env.s"
	@echo "... src/logic.o"
	@echo "... src/logic.i"
	@echo "... src/logic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

